//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesignPatterns_ForHuman_ForCSharp_ForKorean.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesignPatterns_ForHuman_ForCSharp_ForKorean.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;h3 align=&quot;center&quot;&gt;
        ///&lt;a href=&quot;https://github.com/kamranahmedse/design-patterns-for-humans&quot;&gt;인간을 위한 디자인 패턴&lt;/a&gt;을 C#으로 조정
        ///&lt;/h3&gt;
        ///&lt;p align=&quot;center&quot;&gt;&lt;sub&gt;디자인 패턴에 대한 모든 설명은 약간의 변경만 있을 뿐 동일하게 유지됩니다.&lt;/sub&gt;&lt;/p&gt;
        ///
        ///****
        ///
        ///&lt;p align=&quot;center&quot;&gt;
        ///🎉 디자인 패턴에 대한 초간단 설명! 🎉
        ///&lt;/p&gt;
        ///&lt;p align=&quot;center&quot;&gt;
        ///누구나 쉽게 마음을 동요시킬 수 있는 주제. 여기서는 가능한 &lt;i&gt;가장 간단한&lt;/i&gt; 방법으로 설명함으로써 그것들이 당신의 마음(그리고 아마도 내 마음)에 각인되도록 노력합니다.
        ///&lt;/p&gt;
        ///&lt;p align=&quot;center&quot;&gt;
        ///이 문서에서 사용된 코드 스니펫의 전체 길이 예제는 &lt;a href=&quot;https://github.com/anupavanm/csharp-design-patterns-for-humans[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;h3 align=&quot;center&quot;&gt;
        ///Adaptation of &lt;a href=&quot;https://github.com/kamranahmedse/design-patterns-for-humans&quot;&gt;Design Patterns for Humans&lt;/a&gt;  to C#
        ///&lt;/h3&gt;
        ///&lt;p align=&quot;center&quot;&gt;&lt;sub&gt;All the explanation for design patterns stays the same, with minor changes.&lt;/sub&gt;&lt;/p&gt;
        ///
        ///****
        ///
        ///&lt;p align=&quot;center&quot;&gt;
        ///🎉 Ultra-simplified explanation to design patterns! 🎉
        ///&lt;/p&gt;
        ///&lt;p align=&quot;center&quot;&gt;
        ///A topic that can easily make anyone&apos;s mind wobble. Here I try to make them stick in to your mind (and maybe mine) by explaining them in the[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string README___ori {
            get {
                return ResourceManager.GetString("README___ori", resourceCulture);
            }
        }
        
        /// <summary>
        ///   using Builder;
        ///
        ///using Protype;
        ///
        ///using System;
        ///using System.Text;
        ///
        ///namespace DesignPatterns_ForHuman_ForCSharp_ForKorean {
        ///    class Test {
        ///        public static void SimpleFactory_Test() =&gt; SimpleFactory.Test.Run();
        ///        public static void FactoryMethod_Test() =&gt; FactoryMethod.Test.Run();
        ///        public static void AbstractFactory_Test() =&gt; AbstractFactory.Test.Run();
        ///        public static void Builder_Test() =&gt; Builder.Test.Run();
        ///        public static void Protype_Test() =&gt; Protype.Test.Ru[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
